/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDirectSecurOperations.java
 *
 * Created on Jul 21, 2009, 6:20:04 PM
 */

package app.client.ui;

import app.client.controller.RichAction;
import app.client.controller.RichClientActionController;
import app.client.controller.RichClientApplication;
import app.controller.AppActionEvent;
import app.controller.patterns.IApplicationEvent;
import app.domain.model.AppUser;
import java.util.List;
import javax.swing.Action;

/**
 *
 * @author catalin
 */
public class FormDirectUserOperations extends javax.swing.JFrame {

    /** Creates new form FormDirectSecurOperations */
    public FormDirectUserOperations() {
        initComponents();

        RichClientActionController controller =
                (RichClientActionController) RichClientApplication.getActionController();
        RichAction openFormUsers =
                controller.getRichAction("Utilizatori");
        this.btnUsersState.setAction(openFormUsers);

        IApplicationEvent evt = new AppActionEvent("FormDirectSecurOperations", "LoadUsers");
        evt = RichClientApplication.getActionController().actionPerformed(evt);
        this.appUsers.addAll((List) evt.getValue("users"));
        this.bindingGroup.getBinding("bindCboAppUsers").unbind();
        this.bindingGroup.getBinding("bindCboAppUsers").bind();
        //this.cboAppUsers.setSelectedIndex(0);

        evt = new AppActionEvent("FormDirectSecurOperations", "LoadRoles");
        evt = RichClientApplication.getActionController().actionPerformed(evt);
        this.appRoles.addAll((List) evt.getValue("roles"));
        this.bindingGroup.getBinding("bindCboAppRoles").unbind();
        this.bindingGroup.getBinding("bindCboAppRoles").bind();
        //this.cboAppRoles.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        appUsers = new java.util.ArrayList();
        appRoles = new java.util.ArrayList();
        lblExplixatie = new javax.swing.JLabel();
        btnValidateUser = new javax.swing.JButton();
        btnValidateUserRole = new javax.swing.JButton();
        btnSetUserRole = new javax.swing.JButton();
        btnCreateNewUser = new javax.swing.JButton();
        cboAppUsers = new javax.swing.JComboBox();
        cboAppRoles = new javax.swing.JComboBox();
        chkActiv = new javax.swing.JCheckBox();
        txtUsername = new javax.swing.JTextField();
        btnUsersState = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExplixatie.setFont(new java.awt.Font("Tahoma", 3, 11));
        lblExplixatie.setText("Executa actiunile: ");
        lblExplixatie.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnValidateUser.setText("Revalideaza utilizator");
        btnValidateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateUserActionPerformed(evt);
            }
        });

        btnValidateUserRole.setText("Revalidadeaza utilizator pentru role");
        btnValidateUserRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateUserRoleActionPerformed(evt);
            }
        });

        btnSetUserRole.setText("Activeaza/Dezactiveaza rol pentru utilizator");
        btnSetUserRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUserRoleActionPerformed(evt);
            }
        });

        btnCreateNewUser.setText("Creaza utilizator nou:");
        btnCreateNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewUserActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, appUsers, cboAppUsers, "bindCboAppUsers");
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, appRoles, cboAppRoles, "bindCboAppRoles");
        bindingGroup.addBinding(jComboBoxBinding);

        chkActiv.setText("Activ");
        chkActiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActivActionPerformed(evt);
            }
        });

        btnUsersState.setText("Afiseaza stare utilizatori [cu roluri]");

        jLabel1.setText("Tine cont de rubricile-parameri din stinga !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSetUserRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidateUserRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblExplixatie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsersState, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkActiv, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addGap(109, 109, 109))
                    .addComponent(cboAppUsers, 0, 210, Short.MAX_VALUE)
                    .addComponent(cboAppRoles, 0, 210, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsersState, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExplixatie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewUser)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidateUser)
                    .addComponent(cboAppUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidateUserRole)
                    .addComponent(cboAppRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetUserRole)
                    .addComponent(chkActiv))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkActivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActivActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkActivActionPerformed

    private void btnValidateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateUserActionPerformed
        if (this.cboAppUsers.getSelectedItem() != null){
            IApplicationEvent event = new AppActionEvent("FormDirectSecurOperations", "ValidateUser");
            event.setValue("user", this.cboAppUsers.getSelectedItem());
            event = RichClientApplication.getActionController().actionPerformed(event);
        }
}//GEN-LAST:event_btnValidateUserActionPerformed

    private void btnValidateUserRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateUserRoleActionPerformed
        if (this.cboAppUsers.getSelectedItem() != null && this.cboAppRoles.getSelectedItem() != null){
            IApplicationEvent event = new AppActionEvent("FormDirectSecurOperations", "ValidateUserRole");
            event.setValue("user", this.cboAppUsers.getSelectedItem());
            event.setValue("role", this.cboAppRoles.getSelectedItem());
            event = RichClientApplication.getActionController().actionPerformed(event);
        }
}//GEN-LAST:event_btnValidateUserRoleActionPerformed

    private void btnCreateNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewUserActionPerformed
        if (this.txtUsername.getText().isEmpty() == false){
            IApplicationEvent event = new AppActionEvent("FormDirectSecurOperations", "CreateNewUser");
            event.setValue("user", new AppUser(null, this.txtUsername.getText()));
            event = RichClientApplication.getActionController().actionPerformed(event);
            this.appUsers.add(event.getValue("user"));
            this.bindingGroup.getBinding("bindCboAppUsers").unbind();
            this.bindingGroup.getBinding("bindCboAppUsers").bind();
        }
}//GEN-LAST:event_btnCreateNewUserActionPerformed

    private void btnSetUserRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUserRoleActionPerformed
        if (this.cboAppUsers.getSelectedItem() != null && this.cboAppRoles.getSelectedItem() != null){
            IApplicationEvent event = new AppActionEvent("FormDirectSecurOperations", "SetUserRole");
            event.setValue("user", this.cboAppUsers.getSelectedItem());
            event.setValue("role", this.cboAppRoles.getSelectedItem());
            event.setValue("enabled", this.chkActiv.isSelected());
            event = RichClientApplication.getActionController().actionPerformed(event);
        }
    }//GEN-LAST:event_btnSetUserRoleActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDirectUserOperations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.ArrayList appRoles;
    private java.util.ArrayList appUsers;
    private javax.swing.JButton btnCreateNewUser;
    private javax.swing.JButton btnSetUserRole;
    private javax.swing.JButton btnUsersState;
    private javax.swing.JButton btnValidateUser;
    private javax.swing.JButton btnValidateUserRole;
    private javax.swing.JComboBox cboAppRoles;
    private javax.swing.JComboBox cboAppUsers;
    private javax.swing.JCheckBox chkActiv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblExplixatie;
    private javax.swing.JTextField txtUsername;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
