/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on Jan 11, 2009, 8:28:47 PM
 */
package app.client.ui;

import app.client.controller.RichAction;
import app.client.controller.RichClientActionController;
import app.client.controller.RichClientApplication;
import app.client.controller.RichMainForm;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.Action;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author catalin
 */
public class MainForm extends javax.swing.JFrame implements RichMainForm {

    public static final int SINGLE_FRAME_APP = 1;
    public static final int MULTI_FRAME_APP = 2;
    private JDesktopPane desktop;

    public JDesktopPane getDesktop() {
        return desktop;
    }
    private int typeApp = 0;

    /** Creates new form MainForm */
    public MainForm(Boolean showMaximized, int typeApp) {
        initComponents();
        this.typeApp = typeApp;
        if (typeApp == SINGLE_FRAME_APP) {
            desktop = new JDesktopPane();
            desktop.setPreferredSize(new Dimension(800, 500 - this.mainToolbar.getPreferredSize().height));
            this.getContentPane().remove(this.mainToolbar);
            this.setLayout(new BorderLayout());
            this.getContentPane().add(this.mainToolbar, BorderLayout.NORTH);
            this.getContentPane().add(desktop, BorderLayout.CENTER);
            this.pack();
        }
        setApplicationForms();
        if (showMaximized) {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }

    private void setApplicationForms() {
        RichClientActionController controller =
                (RichClientActionController) RichClientApplication.getActionController();
        RichAction openFormClienti =
                controller.getRichAction("Clienti");
        openFormClienti.putValue(Action.SMALL_ICON, this.btnClienti.getIcon());

        this.menuClienti.setAction(openFormClienti);
        this.btnClienti.setAction(openFormClienti);

        RichAction openFormProduse =
                controller.getRichAction("Produse");
        this.menuProduse.setAction(openFormProduse);

        RichAction openFormGridClienti =
                controller.getRichAction("GridClienti");
        this.gridClienti.setAction(openFormGridClienti);

        RichAction openFormFacturi =
                controller.getRichAction("Facturi");
        this.menuFacturi.setAction(openFormFacturi);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainToolbar = new javax.swing.JToolBar();
        btnClienti = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        menuNomenclatoare = new javax.swing.JMenu();
        menuClienti = new javax.swing.JMenuItem();
        menuProduse = new javax.swing.JMenuItem();
        gridClienti = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuFacturi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        mainToolbar.setRollover(true);

        btnClienti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/client/ui/client.png"))); // NOI18N
        btnClienti.setFocusable(false);
        btnClienti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClienti.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/app/client/ui/client.png"))); // NOI18N
        btnClienti.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolbar.add(btnClienti);

        getContentPane().add(mainToolbar, java.awt.BorderLayout.NORTH);

        menuNomenclatoare.setText("Nomenclatoare");

        menuClienti.setText("Clienti");
        menuNomenclatoare.add(menuClienti);

        menuProduse.setText("Produse");
        menuNomenclatoare.add(menuProduse);

        gridClienti.setText("jMenuItem1");
        menuNomenclatoare.add(gridClienti);

        mainMenu.add(menuNomenclatoare);

        jMenu2.setText("Operatiuni");

        menuFacturi.setText("jMenuItem1");
        jMenu2.add(menuFacturi);

        mainMenu.add(jMenu2);

        jMenu3.setText("Asistenta");

        jMenuItem3.setText("Iesire");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        mainMenu.add(jMenu3);

        setJMenuBar(mainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        RichClientApplication.exit();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienti;
    private javax.swing.JMenuItem gridClienti;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JToolBar mainToolbar;
    private javax.swing.JMenuItem menuClienti;
    private javax.swing.JMenuItem menuFacturi;
    private javax.swing.JMenu menuNomenclatoare;
    private javax.swing.JMenuItem menuProduse;
    // End of variables declaration//GEN-END:variables

    public void showForm(Component form) {
        if (form instanceof JFrame && this.typeApp == SINGLE_FRAME_APP) {
            JInternalFrame iFrame = new JInternalFrame();

            if (form instanceof JFrame) {
                iFrame.setContentPane(((JFrame) form).getContentPane());
            } else if (form instanceof JDialog) {
                iFrame.setContentPane(((JDialog) form).getContentPane());
            } else {
                iFrame.setLayout(new BorderLayout());
                iFrame.add(form, BorderLayout.CENTER);
            }

            iFrame.setClosable(true);
            iFrame.setResizable(true);
            iFrame.setMaximizable(true);
            iFrame.setIconifiable(false);

            iFrame.pack();
            desktop.add(iFrame);

            int xMain = desktop.getX();
            int yMain = desktop.getY();
            int wMain = desktop.getWidth();
            int hMain = desktop.getHeight();
            int w = form.getWidth();
            int h = form.getHeight();

            int xiFrame = xMain + ((wMain - w) / 10);
            int yiFrame = yMain + ((hMain - h) / 16);

            iFrame.setLocation(xiFrame, yiFrame);
            iFrame.setVisible(true);

        } else {
            int xMain = this.getX();
            int yMain = this.getY();
            int wMain = this.getWidth();
            int hMain = this.getHeight();
            int w = form.getWidth();
            int h = form.getHeight();

            int xiFrame = xMain + ((wMain - w) / 6);
            int yiFrame = yMain + ((hMain - h) / 3);
            form.setLocation(xiFrame, yiFrame);
            form.setVisible(true);
        }

    }
}
